### ISSUE TITLE
Problema con las rutas relativas en Windows

### ISSUE THREAD

**Issue by alexSelah** [ppizarror/python-paint#1]
Hola, Hay un problema al ejecutar el archivo en Windows a causa de las rutas relativas que se usan.

El tracelog es el siguiente:

`Traceback (most recent call last):
  File "C:\Users\OP231\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "h:\OP231\Documents\Programación\Python\python-paint\Paint.py", line 224, in <lambda>
    Button(ActiveColor,text="Color principal",relief=FLAT,command=lambda:self.cambiarColor("activo"),width=10).pack()
  File "h:\OP231\Documents\Programación\Python\python-paint\Paint.py", line 316, in cambiarColor
    a = pyv("Cambiar color",DATAICONS+"color.ico","cambiarcolor",(280,440))
  File "h:\OP231\Documents\Programación\Python\python-paint\pyv.py", line 27, in __init__
    self.root.iconbitmap(bitmap=icon)
  File "C:\Users\OP231\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2071, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)`

Lo he solucionado con el siguiente trozo de código en la declaración de Constantes de carpetas:

`import os
DIRNAME = os.path.dirname(__file__)
DATAFOLDER = os.path.join(DIRNAME, 'Data\\')`

Lo demás sigue igual.

Voy a intentar crear un fork de tu proyecto.
Por cierto, felicidades, está muy bien :)

**Comment by ppizarror** [comment]
Hola! Si quieres puedes hacer un pull request del proyecto o modificarlo a
gusto si quieres añadir otras características. Yo hice este proyecto para
aprender tkinter y hace años que no lo toco.

Saludos!

**Comment by alexSelah** [comment]
Gracias!
Estoy intentando aprender python, al mismo tiempo que tengo un proyecto en mente (un gestor de mapas con capas), y tu programa es genial. Además, está muy bien comentado.
Vengo de Java, C y otros lenguajes, así que tardaré bastante en aprender bien Python.
Un saludo.
